# Generated by Django 2.1.1 on 2018-12-29 20:49

from django.db import migrations, models


def create_initial_entries(apps, schema_editor):
    SpecialBanner = apps.get_model("gc_toolbox", "SpecialBanner")
    SpecialBanner.objects.create(
        gc_code="GC24XB5",
        image_url="http://wampenschleifer.de/Logos/GC24XB5.jpg",
        reason="Banner on special page",
    )
    SpecialBanner.objects.create(
        gc_code="GC2PHWJ",
        image_url="http://wampenschleifer.de/Logos/GC2PHWJ.jpg",
        reason="",
    )
    SpecialBanner.objects.create(
        gc_code="GC2PHWK",
        image_url="http://wampenschleifer.de/Logos/GC2PHWK.jpg",
        reason="Banner on special page",
    )
    SpecialBanner.objects.create(
        gc_code="GC2KCRY",
        image_url="http://wampenschleifer.de/Logos/GC2KCRY.jpg",
        reason="Banner on special page",
    )
    SpecialBanner.objects.create(
        gc_code="GC2PHWN",
        image_url="http://wampenschleifer.de/Logos/GC2PHWN.jpg",
        reason="Banner on special page",
    )
    SpecialBanner.objects.create(
        gc_code="GC2PHWG",
        image_url="http://wampenschleifer.de/Logos/GC2PHWG.jpg",
        reason="Banner on special page",
    )
    SpecialBanner.objects.create(
        gc_code="GC2PHWE",
        image_url="http://wampenschleifer.de/Logos/GC2PHWE.jpg",
        reason="Banner on special page",
    )
    SpecialBanner.objects.create(
        gc_code="GC2PHWB",
        image_url="http://wampenschleifer.de/Logos/GC2PHWB.jpg",
        reason="Banner on special page",
    )
    SpecialBanner.objects.create(
        gc_code="GC3REGY",
        image_url="http://wampenschleifer.de/Logos/GC3REGY.jpg",
        reason="Banner on special page",
    )
    SpecialBanner.objects.create(
        gc_code="GC2GJY9",
        image_url="http://wampenschleifer.de/Logos/GC2GJY9.jpg",
        reason="Banner on special page",
    )
    SpecialBanner.objects.create(
        gc_code="GC2YMKA",
        image_url="http://wampenschleifer.de/Logos/GC2YMKA.jpg",
        reason="Banner on special page",
    )
    SpecialBanner.objects.create(
        gc_code="GC2KCRW",
        image_url="http://wampenschleifer.de/Logos/GC2KCRW.jpg",
        reason="Banner on special page",
    )
    SpecialBanner.objects.create(
        gc_code="GC26D16",
        image_url="http://wampenschleifer.de/Logos/GC26D16.jpg",
        reason="Banner on special page",
    )
    SpecialBanner.objects.create(
        gc_code="GC2FX2D",
        image_url="http://wampenschleifer.de/Logos/GC2FX2D.jpg",
        reason="Banner on special page",
    )
    SpecialBanner.objects.create(
        gc_code="GC3BZ1Q",
        image_url="http://wampenschleifer.de/Logos/GC3BZ1Q.jpg",
        reason="Banner on special page",
    )
    SpecialBanner.objects.create(
        gc_code="GC47M25",
        image_url="http://wampenschleifer.de/Logos/GC47M25.jpg",
        reason="Banner on special page",
    )
    SpecialBanner.objects.create(
        gc_code="GC511AX",
        image_url="http://wampenschleifer.de/Logos/GC511AX.jpg",
        reason="Banner on special page",
    )
    SpecialBanner.objects.create(
        gc_code="GC537V1",
        image_url="http://wampenschleifer.de/Logos/GC537V1.jpg",
        reason="Banner on special page",
    )
    SpecialBanner.objects.create(
        gc_code="GC5A4X9",
        image_url="http://wampenschleifer.de/Logos/GC5A4X9.jpg",
        reason="Banner on special page",
    )
    SpecialBanner.objects.create(
        gc_code="GCZB0W",
        image_url="http://fs5.directupload.net/images/user/170406/o4c8e44b.png",
        reason='Banner before keyword "banner"',
    )
    SpecialBanner.objects.create(
        gc_code="GC52VPD",
        image_url=None,
        reason="misleading the parser (refers to banner in another cache)",
    )
    SpecialBanner.objects.create(
        gc_code="GC52VMR",
        image_url=None,
        reason="misleading the parser (refers to banner in another cache)",
    )
    SpecialBanner.objects.create(
        gc_code="GC52VNZ",
        image_url=None,
        reason="misleading the parser (refers to banner in another cache)",
    )
    SpecialBanner.objects.create(
        gc_code="GC52VQA",
        image_url=None,
        reason="misleading the parser (refers to banner in another cache)",
    )
    SpecialBanner.objects.create(
        gc_code="GC52VR5",
        image_url=None,
        reason="misleading the parser (refers to banner in another cache)",
    )
    SpecialBanner.objects.create(
        gc_code="GC52W0J",
        image_url=None,
        reason="misleading the parser (refers to banner in another cache)",
    )
    SpecialBanner.objects.create(
        gc_code="GC52W10",
        image_url=None,
        reason="misleading the parser (refers to banner in another cache)",
    )
    SpecialBanner.objects.create(
        gc_code="GC52W7B",
        image_url=None,
        reason="misleading the parser (refers to banner in another cache)",
    )
    SpecialBanner.objects.create(
        gc_code="GC52W7T",
        image_url=None,
        reason="misleading the parser (refers to banner in another cache)",
    )
    SpecialBanner.objects.create(
        gc_code="GC52W87",
        image_url=None,
        reason="misleading the parser (refers to banner in another cache)",
    )
    SpecialBanner.objects.create(
        gc_code="GC6BAZ8",
        image_url=None,
        reason="misleading the parser (image refers to cache itself but is no banner)",
    )
    SpecialBanner.objects.create(
        gc_code="GC4TCM0", image_url=None, reason="parsed an emoji as banner"
    )
    SpecialBanner.objects.create(
        gc_code="GC28TMR",
        image_url=None,
        reason="misleading by linking the cache from a non banner image",
    )
    SpecialBanner.objects.create(
        gc_code="GC28TMN",
        image_url=None,
        reason="misleading by linking the cache from a non banner image",
    )
    SpecialBanner.objects.create(
        gc_code="GC28TMW",
        image_url=None,
        reason="misleading by linking the cache from a non banner image",
    )
    SpecialBanner.objects.create(
        gc_code="GC28TMK",
        image_url=None,
        reason="misleading by linking the cache from a non banner image",
    )
    SpecialBanner.objects.create(
        gc_code="GC4WDV0", image_url=None, reason="parsed tradi image as banner"
    )
    SpecialBanner.objects.create(
        gc_code="GC28TMB",
        image_url=None,
        reason="misleading by linking the cache from a non banner image",
    )
    SpecialBanner.objects.create(
        gc_code="GC28TMA",
        image_url=None,
        reason="misleading by linking the cache from a non banner image",
    )
    SpecialBanner.objects.create(
        gc_code="GC28TMP",
        image_url=None,
        reason="misleading by linking the cache from a non banner image",
    )
    SpecialBanner.objects.create(
        gc_code="GC28TMT",
        image_url=None,
        reason="misleading by linking the cache from a non banner image",
    )
    SpecialBanner.objects.create(
        gc_code="GC28TMF",
        image_url=None,
        reason="misleading by linking the cache from a non banner image",
    )
    SpecialBanner.objects.create(
        gc_code="GC28TMX",
        image_url=None,
        reason="misleading by linking the cache from a non banner image",
    )
    SpecialBanner.objects.create(
        gc_code="GC28TMH",
        image_url=None,
        reason="misleading by linking the cache from a non banner image",
    )
    SpecialBanner.objects.create(
        gc_code="GC2JMDK", image_url=None, reason="ape head as banner"
    )
    SpecialBanner.objects.create(
        gc_code="GC2PG8Q", image_url=None, reason="riddle as banner"
    )
    SpecialBanner.objects.create(
        gc_code="GC28TMC",
        image_url=None,
        reason="misleading by linking the cache from a non banner image",
    )
    SpecialBanner.objects.create(
        gc_code="GC28TMG",
        image_url=None,
        reason="misleading by linking the cache from a non banner image",
    )
    SpecialBanner.objects.create(
        gc_code="GC28TMQ",
        image_url=None,
        reason="misleading by linking the cache from a non banner image",
    )
    SpecialBanner.objects.create(
        gc_code="GC28TMY",
        image_url=None,
        reason="misleading by linking the cache from a non banner image",
    )
    SpecialBanner.objects.create(
        gc_code="GC28TME",
        image_url=None,
        reason="misleading by linking the cache from a non banner image",
    )
    SpecialBanner.objects.create(
        gc_code="GC5DZWP", image_url=None, reason="emoji as banner"
    )
    SpecialBanner.objects.create(
        gc_code="GC6D17N", image_url=None, reason="image is not a banner"
    )
    SpecialBanner.objects.create(
        gc_code="GC5DZWR", image_url=None, reason="image is not a banner"
    )
    SpecialBanner.objects.create(
        gc_code="GC3NZTR", image_url=None, reason="image is not a banner"
    )
    SpecialBanner.objects.create(
        gc_code="GC2PG8R", image_url=None, reason="image is not a banner"
    )
    SpecialBanner.objects.create(
        gc_code="GC3PFZW", image_url=None, reason="image is not a banner"
    )
    SpecialBanner.objects.create(
        gc_code="GC5F7HX", image_url=None, reason="image is not a banner"
    )
    SpecialBanner.objects.create(
        gc_code="GC2PG8P", image_url=None, reason="image is not a banner"
    )
    SpecialBanner.objects.create(
        gc_code="GC1KWDQ", image_url=None, reason="image is not a banner"
    )
    SpecialBanner.objects.create(
        gc_code="GC4RANA", image_url=None, reason="image is not a banner"
    )
    SpecialBanner.objects.create(
        gc_code="GC3P8CH", image_url=None, reason="image is not a banner"
    )
    SpecialBanner.objects.create(
        gc_code="GC5DZT8", image_url=None, reason="image is not a banner"
    )
    SpecialBanner.objects.create(
        gc_code="GC6D15P", image_url=None, reason="image is not a banner"
    )
    SpecialBanner.objects.create(
        gc_code="GC6MJ24", image_url=None, reason="mistakes linked list as banner"
    )
    SpecialBanner.objects.create(gc_code="GC2DM44", image_url=None, reason="no banner")
    SpecialBanner.objects.create(
        gc_code="GC1851C", image_url=None, reason="image is not a banner"
    )
    SpecialBanner.objects.create(
        gc_code="GC5DZTZ", image_url=None, reason="image is not a banner"
    )
    SpecialBanner.objects.create(
        gc_code="GC6EJF4", image_url=None, reason="image is not a banner"
    )
    SpecialBanner.objects.create(gc_code="GC5DZW6", image_url=None, reason="no banner")
    SpecialBanner.objects.create(gc_code="GC1QM7B", image_url=None, reason="no banner")
    SpecialBanner.objects.create(
        gc_code="GC2PG8N", image_url=None, reason="riddle as banner"
    )
    SpecialBanner.objects.create(
        gc_code="GC2PG8M", image_url=None, reason="riddle as banner"
    )
    SpecialBanner.objects.create(
        gc_code="GC4YAEY",
        image_url="http://imgcdn.geocaching.com/cache/large/55fcadb9-4464-483c-b43a-8152cf51f422.jpg",
        reason="Banner was deleted",
    )
    SpecialBanner.objects.create(
        gc_code="GC4432N",
        image_url=None,
        reason="reference to main cache looks like a banner",
    )
    SpecialBanner.objects.create(gc_code="GC469TG", image_url=None, reason="No banner")
    SpecialBanner.objects.create(gc_code="GC11JM6", image_url=None, reason="No banner")
    SpecialBanner.objects.create(gc_code="GC6PHH7", image_url=None, reason="No banner")


class Migration(migrations.Migration):
    dependencies = [
        ("gc_toolbox", "0003_bannerdimension"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialBanner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gc_code", models.CharField(max_length=10)),
                ("image_url", models.CharField(blank=True, max_length=255, null=True)),
                ("reason", models.CharField(max_length=100)),
            ],
        ),
        migrations.RunPython(create_initial_entries),
    ]
