# Generated by Django 3.2.3 on 2021-05-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gc_toolbox", "0004_specialbanner"),
    ]

    operations = [
        migrations.AddField(
            model_name="bannerdimension",
            name="gc_code",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bannerdimension",
            name="url",
            field=models.CharField(default="", max_length=1024),
            preserve_default=False,
        ),
    ]
