# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CacheCoordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gc_code', models.CharField(max_length=10)),
                ('latitude', models.CharField(max_length=15)),
                ('longitude', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cachecoordinates',
            unique_together=set([('gc_code', 'latitude', 'longitude')]),
        ),
    ]
