# Generated by Django 3.2.3 on 2021-05-23 21:50

import baronbale_website.banner_parser.generators.ticket_id_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnqueuedBannerParserJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(default=baronbale_website.banner_parser.generators.ticket_id_generator.generate_ticket_id, max_length=100)),
                ('email_address_to_notify', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_file', models.FileField(upload_to='', verbose_name='GPX-File or Zip Archive')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
