# Generated by Django 3.2.3 on 2021-05-29 13:08
from typing import List

from django.db import migrations


def import_special_banners(apps, schema_editor) -> None:
    SpecialBanner = apps.get_model("gc_toolbox", "SpecialBanner")
    special_banners: List[SpecialBanner] = SpecialBanner.objects.all()

    BannerCache = apps.get_model("banner_parser", "BannerCache")
    for special_banner in special_banners:
        BannerCache.objects.create(
            gc_code=special_banner.gc_code,
            image_url=special_banner.image_url,
            reason=special_banner.reason,
            permanent=True,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("banner_parser", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(import_special_banners),
    ]
